### PR TITLE
Fix Broken Links

### PR DESCRIPTION
**Pull request by justindhillon**
There are multiple broken links in this project. Here are the ones I have fixed.

https://github.com/JackFromNice --> https://twitter.com/medenstephane because his github account does not exist anymore.

https://www.xxgame.net --> http://xxgame.net/

https://github.com/Adubbz/Tinfoil/ --> https://github.com/Adubbz because his repo does not exist anymore

https://github.com/Swarsele --> https://www.instagram.com/swarsele/?hl=en because his github account does not exist anymore.

https://github.com/developer_su --> https://github.com/developersu

https://repo.redrise.ru/releases --> https://repo.redrise.ru/#/releases

These broken links where found with [link-inspector](https://github.com/justindhillon/link-inspector)

### CODE REVIEW

**Comment by developersu** [comment]
Hi, thank you for bringing this up. Please exclude next ones:

Should be left as is, to those who needs it could check Web Archive (Wayback Machine):
> https://github.com/JackFromNice --> https://twitter.com/medenstephane because his github account does not exist anymore.

> https://github.com/Adubbz/Tinfoil/ --> https://github.com/Adubbz because his repo does not exist anymore

> https://github.com/Swarsele --> https://www.instagram.com/swarsele/?hl=en because his github account does not exist anymore.

This is correct, should be left as is:
> https://repo.redrise.ru/releases --> https://repo.redrise.ru/#/releases

**Comment by justindhillon** [comment]
https://repo.redrise.ru/releases returns a 404

Screenshot from 2023-11-08 09-06-20

Just double checking that this is the intended behavior.

**Comment by justindhillon** [comment]
I have reverted the three links that should be kept as archives.

https://github.com/JackFromNice

https://github.com/Adubbz/Tinfoil/

https://github.com/Swarsele

**Comment by developersu** [comment]
> Just double checking that this is the intended behavior.

Yes, this is correct and intended behavior.

Also next line should be left as is 
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
---
`pom.xml` is not for humans so it's fine when something doesn't work in browser.

Regarding first case, it's fine because this is not actually a link, it's kinda a part or prefix. E.g. [this link is valid and works](https://repo.redrise.ru/releases/ru/redrise/libKonogonka/0.1/libKonogonka-0.1.jar) and [this one does not](https://repo.redrise.ru/releases/#/ru/redrise/libKonogonka/0.1/libKonogonka-0.1.jar)

As for the second note, it's done as [maven documentation](https://maven.apache.org/pom.html) says so no need to fix what is not broken.

Thanks!

**Comment by justindhillon** [comment]
Thanks for the feedback! The line in pom.xml has been reverted. https://repo.redrise.ru/releases has also been reverted.

**Comment by developersu** [comment]
Thanks!

**Pull request merged**
